# https://github.com/AkhileshNS/heroku-deploy
  
name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.0.5 # This is the action
        if: "contains(github.event.head_commit.message, 'deploy')"
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "spacedrop-app" #Must be unique in Heroku
          heroku_email: "hr.dev@icloud.com"
#           buildpack: "SOME BUILDPACK" #OPTIONAL
